# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Public Artefacts

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup KeyStore File
      run: echo keytool -genkey -v -keystore myapp.keystore -alias key -keyalg RSA -keysize 2048 -validity 10000
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install .NET MAUI
      run: dotnet workload install maui
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -f:net6.0-android -c:Release /p:AndroidSigningKeyPass=mypassword /p:AndroidSigningStorePass=mypassword
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with: 
        path: |
          ./**/*.aab
          ./**/*.apk
        
    
